name: Java CI with Maven

on:
  workflow_dispatch:  # Enables manual trigger
  push:
    branches: [ "master" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK for Java (if required for your project)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      # Cache Maven dependencies for faster builds (if using Maven)
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Run the Selenium tests
      - name: Run tests
        run: mvn clean install -DskipTests=false
